version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "8"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
      - -tags=osusergo,netgo
      - -installsuffix=cgo
    ldflags:
      - "-s -w -buildid= -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}"
    gcflags:
      - "all=-m=0 -l=2 -dwarf=false"

upx:
  - enabled: true
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    compress: best
    lzma: true
    brute: true

dockers:
  - image_templates:
      - "braveokafor/go-mail-api:v{{ .Version }}-amd64"
      - "ghcr.io/braveokafor/go-mail-api:v{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url={{.GitURL}}"
      - --label=org.opencontainers.image.source={{.GitURL}}"
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
      - --platform=linux/amd64
  - image_templates:
      - "braveokafor/go-mail-api:v{{ .Version }}-arm64"
      - "ghcr.io/braveokafor/go-mail-api:v{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url={{.GitURL}}"
      - --label=org.opencontainers.image.source={{.GitURL}}"
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
      - --platform=linux/arm64
    goarch: arm64

docker_manifests:
  - name_template: "braveokafor/go-mail-api:v{{ .Version }}"
    image_templates:
      - "braveokafor/go-mail-api:v{{ .Version }}-amd64"
      - "braveokafor/go-mail-api:v{{ .Version }}-arm64"
  - name_template: "ghcr.io/braveokafor/go-mail-api:v{{ .Version }}"
    image_templates:
      - "ghcr.io/braveokafor/go-mail-api:v{{ .Version }}-amd64"
      - "ghcr.io/braveokafor/go-mail-api:v{{ .Version }}-arm64"

nfpms:
  - maintainer: Brave Okafor <okaforbrave@gmail.com>
    description: Go Mail API is a simple REST API for sending email notifications via SMTP.
    homepage: https://github.com/braveokafor/go-mail-api
    license: MIT
    formats:
      - deb
      - rpm
      - apk

release:
  draft: true
  github:
    owner: braveokafor
    name: go-mail-api

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

sboms:
  - artifacts: archive