name: Build Go-Mail-API Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # 3. 设置 Docker Buildx (支持多平台)
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # 4. 编译二进制 + 构建 Docker 镜像
      - name: Build Docker image
        run: |
          # 构建镜像（multi-stage Dockerfile 会自动编译 go-mail-api）
          docker build -t go-mail-api:latest .
          # 保存为 tar 文件
          docker save go-mail-api:latest -o go-mail-api.tar

      # 5. 上传 Docker 镜像 tar 到 GitHub Actions Artifact
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-mail-api-docker
          path: go-mail-api.tar
