name: Go Releaser

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

env:
  PACKAGE_NAME: go-mail-api
  DOCKERFILE_PATH: Dockerfile
  DOCKER_CONTEXT_PATH: .
  DOCKER_IMAGE_NAMES: |
    ghcr.io/${{ github.actor }}/go-mail-api


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (no push)
        run: |
          docker build -t go-mail-api:latest .
          docker save go-mail-api:latest -o go-mail-api.tar
          
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-mail-api-image
          path: go-mail-api.tar

