name: Build Go-Mail-API Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # 3. 编译 Go 二进制
      - name: Build Go binary
        run: |
          # 确保编译出来的二进制在工作目录
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o go-mail-api ./cmd
          ls -lh go-mail-api

      # 4. 设置 Docker Buildx (支持多平台)
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # 5. 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t go-mail-api:latest .

      # 6. 保存镜像为 tar 文件
      - name: Save Docker image to tar
        run: docker save go-mail-api:latest -o go-mail-api.tar

      # 7. 上传 tar 到 GitHub Actions Artifact
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-mail-api-docker
          path: go-mail-api.tar
